### PR TITLE
Fix fetch scoping for cloudflare workers

### LINKED ISSUE #134: TypeError: Illegal invocation | Cloudflare workers
Trying to run replicate on cloudflare workers but can't seem to run any model:

```
const model =
    "stability-ai/stable-diffusion:27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478";
  const input = {
    prompt: "a 19th century portrait of a raccoon gentleman wearing a suit",
  };
  const output = await replicate.run(model, { input });
```

I keep getting this error:
```
A promise rejection was handled asynchronously. This warning occurs when attaching a catch handler to a promise after it rejected. (rejection #6)
Trace: TypeError: Illegal invocation
    at Object.apply (index.js:58:24)
    at withAutomaticRetries.shouldRetry.shouldRetry (index.js:507:70)
    at withAutomaticRetries (index.js:129:14)
    at async Replicate2.request (index.js:507:26)
    at async Replicate2.createPrediction (index.js:227:24)
    at async Replicate2.run (index.js:433:26)
    at async index.js:4629:14
    at async index.js:2745:7
    at async index.js:2072:62
    at async jsonError (index.js:4652:12) {
  stack: TypeError: Illegal invocation
    at Object.apply …2072:62
    at async jsonError (index.js:4652:12),
  message: Illegal invocation
}
```

I've tried overiding fetch but that doesn't seem to solve the issue

### PR DESCRIPTION
**Pull request by robertlong**
I was having the same bug described in #134 and traced it to this line.

Still trying to wrap my head around why `this.fetch` cannot be invoked when the wrapping closure is called inside `withAutomaticRetries`. And why does this only happen in cloudflare workers? Saving the fetch method to a temporary variable seems to work though.

Fixes #134

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -211,7 +211,8 @@ class Replicate {
     const shouldRetry = method === 'GET' ?
       (response) => (response.status === 429 || response.status >= 500) :
       (response) => (response.status === 429);
-    const response = await withAutomaticRetries(async () => this.fetch(url, init), { shouldRetry });
+    const _fetch = this.fetch;
```
Comment (mattt) [inline index.js:214]:
```suggestion
    // Workaround to fix `TypeError: Illegal invocation` error in Cloudflare Workers
    // https://github.com/replicate/replicate-javascript/issues/134
    const _fetch = this.fetch;
```

**Review by mattt — APPROVED** [review]
@robertlong Thanks so much for sharing this fix! I'm also confused about why this is necessary. ["Cloudflare Workers uses the V8 JavaScript engine"](https://developers.cloudflare.com/workers/runtime-apis/web-standards/), but something in their runtime seems to cause JavaScript context to behave differently.

Whatever the reason, I'm happy the fix you've found is small and unlikely to cause issues with other environments.
